# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default

variables:
- name: SYNCFUSION_LICENSE
  value: Mgo+DSMBMAY9C3t2UFhhQlBMfVpdXGFWfFN0QXNYfVRwdF9GYEwgOX1dQl9nSXxSdERiW3ddcHxTQWg=

steps:
- script: npm init -y
  displayName: 'Initialize package.json'

- script: call npm install
  displayName: 'Install node modules'

- script: call npx syncfusion-license activate
  displayName: 'Activate Syncfusion License'
  env:
    SYNCFUSION_LICENSE: $(SYNCFUSION_LICENSE)
